#!/bin/sh -x
 
export NETREXX_JAVA=-mx64m

rm *.class
rm *.crossref
rm *.java
rm *.java.keep

java -ms4M $NETREXX_JAVA -cp ~/lib/NetRexxC.jar:. COM.ibm.netrexx.process.NetRexxC -savelog -nocompile link pipe _stage stage StageError node utils DString IRange RingBuf ThreadPool ThreadQ RunnablePool
ls *.java.keep | cut -f1-2 -d. | xargs -I{} mv {}.keep {}
javac -cp ~/lib/NetRexxC.jar:. -O -deprecation link.java pipe.java _stage.java stage.java StageError.java node.java utils.java DString.java IRange.java RingBuf.java ThreadPool.java ThreadQ.java RunnablePool.java

java -cp ~/lib/NetRexxC.jar:.:.. -ms4M COM.ibm.netrexx.process.NetRexxC -savelog compiler filterNjp pipe2nrx processNjp readconfig readgroup writepipe
